export const mockWishes = [
  "Chúc mừng kỷ niệm thành lập! Chúc tổ chức ngày càng phát triển bền vững và vươn xa hơn nữa.",
  "Xin gửi lời chúc tốt đẹp nhất nhân dịp kỷ niệm thành lập, chúc công ty gặt hái nhiều thành công mới.",
  "Kính chúc toàn thể tập thể luôn đoàn kết, vững mạnh và gặt hái nhiều thành tựu rực rỡ.",
  "Chúc mừng hành trình đáng nhớ, chúc tổ chức tiếp tục tỏa sáng trong những năm tiếp theo.",
  "Một chặng đường đã qua thật đáng tự hào, chúc tập thể sẽ tiếp tục phát triển vượt bậc.",
  "Xin gửi lời tri ân và lời chúc mừng đến toàn bộ cán bộ, nhân viên nhân ngày thành lập.",
  "Chúc mừng kỷ niệm thành lập, chúc cho tương lai sẽ còn nhiều cột mốc vinh quang hơn nữa.",
  "Kính chúc tổ chức luôn giữ vững tinh thần đổi mới, sáng tạo và phát triển bền vững.",
  "Chúc cho tập thể ngày càng đoàn kết, bứt phá và đạt được nhiều dấu mốc đáng nhớ.",
  "Nhân dịp kỷ niệm thành lập, chúc tổ chức ngày càng thịnh vượng và khẳng định vị thế.",
  "Chặng đường phát triển vừa qua thật đáng tự hào, chúc tiếp tục gặt hái nhiều thành công mới.",
  "Xin chúc tổ chức không ngừng lớn mạnh, đạt được nhiều thành tích vẻ vang.",
  "Kính chúc quý công ty thêm nhiều năm thành công rực rỡ, lan tỏa giá trị đến cộng đồng.",
  "Chúc mừng ngày thành lập, chúc tổ chức tiếp tục là điểm tựa vững chắc cho nhân viên và đối tác.",
  "Một tập thể đoàn kết là sức mạnh to lớn, chúc tổ chức ngày càng gắn bó và phát triển.",
  "Nhân ngày đặc biệt này, chúc tổ chức luôn giữ ngọn lửa nhiệt huyết và đam mê.",
  "Chúc mừng kỷ niệm, chúc tập thể tiếp tục chinh phục nhiều đỉnh cao mới.",
  "Xin gửi lời chúc sức khỏe, hạnh phúc và thành công đến toàn thể cán bộ, nhân viên.",
  "Chúc cho tổ chức ngày càng vững vàng, tự tin trên hành trình phát triển.",
  "Kỷ niệm thành lập là cột mốc ý nghĩa, chúc công ty đạt được nhiều kỳ tích lớn lao.",
  "Xin chúc tập thể luôn giữ tinh thần khởi nghiệp, đổi mới và sáng tạo không ngừng.",
  "Nhân dịp đặc biệt, chúc công ty ngày càng uy tín, vững mạnh và trường tồn.",
  "Một hành trình tự hào, chúc tổ chức tiếp tục khẳng định vị thế trên thị trường.",
  "Chúc công ty luôn là môi trường làm việc lý tưởng, nơi ươm mầm tài năng.",
  "Xin gửi lời chúc mừng nồng nhiệt nhất nhân dịp kỷ niệm, chúc cho tương lai rực rỡ.",
  "Chúc công ty luôn giữ được sự phát triển bền vững và lan tỏa giá trị nhân văn.",
  "Kính chúc tập thể đạt được nhiều mục tiêu lớn hơn trong chặng đường sắp tới.",
  "Chúc mừng kỷ niệm thành lập, chúc tổ chức ngày càng tiến xa và bền vững.",
  "Nhân dịp ý nghĩa này, chúc toàn thể công ty dồi dào sức khỏe, hạnh phúc và thành công.",
  "Xin chúc mừng một hành trình vẻ vang, chúc công ty ngày càng phát triển vượt bậc.",
];
